language: node_js
node_js:
  - "11"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn tsc
  - yarn test
  - yarn build

deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_USER_EMAIL
    api_key: $NPM_AUTH_TOKEN
    on:
      tags: true
